import 'package:flutter/services.dart';
import 'package:injectable/injectable.dart';
import 'package:news_glance/domain_services/sharing_service.dart';
import 'package:share_plus/share_plus.dart';

@LazySingleton(as: SharingService)
class SharingServiceImpl implements SharingService {
  @override
  Future<SharingResult> shareBriefing(String text) async {
    final String contentToShare =
        '''
News Glance

$text

Generated by News Glance - AI-powered daily situational awareness.
''';

    try {
      final ShareResult result = await SharePlus.instance.share(
        ShareParams(text: contentToShare),
      );

      if (result.status == ShareResultStatus.success) {
        return SharingResult.shared;
      }

      if (result.status == ShareResultStatus.unavailable) {
        await _copyToClipboard(contentToShare);
        return SharingResult.copiedToClipboard;
      }

      return SharingResult.failed;
    } catch (e) {
      await _copyToClipboard(contentToShare);
      return SharingResult.copiedToClipboard;
    }
  }

  @override
  Future<void> shareUrl(String url, {String? title}) async {
    await SharePlus.instance.share(ShareParams(text: url, subject: title));
  }

  @override
  Future<void> copyToClipboard(String text) async {
    await _copyToClipboard(text);
  }

  Future<void> _copyToClipboard(String text) async {
    await Clipboard.setData(ClipboardData(text: text));
  }
}
