name: Code Quality

on: [ push ]

jobs:
  check_lint_errors:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Get packages
        run: flutter pub get

      - name: Check lint errors
        run: flutter analyze .

      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 35